wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1653851405
    t:
      1:
      - 1
      - 55
      3:
      - 15
      4: 3.9.12
      5: 0.12.17
      8:
      - 1
      - 5
