wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1653852391
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 13
      4: 3.9.12
      5: 0.12.17
      8:
      - 1
      - 5
    visualize:
      syn_histogram:
        panel_config:
          fieldSettings:
            value: syn_conc
          panelDefId: wandb/histogram/v0
          stringSettings:
            title: Histogram of Original Syn data
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: syn_histogram_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
