wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1655217231
    t:
      1:
      - 5
      - 53
      - 55
      3:
      - 15
      4: 3.10.4
      5: 0.12.16
      8:
      - 1
      - 5
