wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.4
    start_time: 1655352619
    t:
      1:
      - 5
      - 53
      - 55
      3:
      - 15
      - 19
      4: 3.10.4
      5: 0.12.16
      8:
      - 1
      - 5
ik_rq_l:
  desc: null
  value: 2
ik_sf:
  desc: null
  value: 1
ltt_a:
  desc: null
  value: 0.5
ltt_rbf:
  desc: null
  value: 365
ltt_sf:
  desc: null
  value: 1
nk_rbf_l:
  desc: null
  value: 0.1
nk_sf:
  desc: null
  value: 0.0025000000000000005
nk_wnk_nl:
  desc: null
  value: 0.0025000000000000005
sk_a:
  desc: null
  value: 0.5
sk_ess_l:
  desc: null
  value: 1
sk_ess_p:
  desc: null
  value: 365
sk_rbf_l:
  desc: null
  value: 1
sk_sf:
  desc: null
  value: 4
test_size:
  desc: null
  value: 0.9
training_size:
  desc: null
  value: 0.1
